# Generated by Django 5.1.6 on 2025-04-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='species',
        ),
        migrations.AddField(
            model_name='plant',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
